### ISSUE TITLE
Error during integratethis move2archive in Windows 11 System Explorer

### ISSUE THREAD

**Issue by chaicurioquest** [novoid/move2archive#12] opened 2024-06-23 06:33 UTC
Hi,
I am getting an error during  integration of move2archive in Windows Explorer using integratethis. 

In Command _line(cmd):_
`C:\User\Name>integratethis move2archive --confirm`
**"ERROR    Sorry, this tool is only configured to integrate to Windows Explorer. More to come in the future".**

However, I can integrate appendfilename, date2name, filetags and Tagtree variants in Windows Explorer.

**Comment by novoid** [comment] 2024-06-24 11:33
Duplicate of https://github.com/novoid/move2archive/issues/11

**Closed by novoid** 2024-06-24 11:33 UTC
